apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: demand
spec:
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - on-demand
  - key: capacity-spread
    operator: In
    values:
    - "1"
    - "2"
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  kubeletConfiguration:
    maxPods: 30
  limits:
    resources:
      cpu: "500"
  ttlSecondsAfterEmpty: 30
  
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: kr-hl-01
  securityGroupSelector:
    karpenter.sh/discovery: kr-hl-01