apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: spot
spec:
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: capacity-spread
    operator: In
    values:
    - "3"
    - "4"
  - key: kubernetes.io/arch
    operator: In
    values:
    - amd64
  kubeletConfiguration:
    maxPods: 30
  limits:
    resources:
      cpu: "500"
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: kr-hl-01
  securityGroupSelector:
    karpenter.sh/discovery: kr-hl-01