apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: karpenter.k8s.aws/instance-family
      operator: In
      values: [c5, m5]
    - key: karpenter.k8s.aws/instance-size
      operator: NotIn
      values: [nano, micro, small, large]
    - key: node.kubernetes.io/instance-type
      operator: NotIn
      values: [m5.24xlarge]
  limits:
    resources:
      cpu: 10000
  ttlSecondsAfterEmpty: 30
  provider:
    subnetSelector:
      karpenter.sh/discovery: "vedmich-kr01-827-01" 
    securityGroupSelector:
      karpenter.sh/discovery: "vedmich-kr01-827-01" 
