apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 10000
  provider:
    subnetSelector:
      karpenter.sh/discovery: vedmich-karpenter-02
    securityGroupSelector:
      karpenter.sh/discovery: vedmich-karpenter-02
  ttlSecondsAfterEmpty: 30