apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: vedmich-ca-demo
  region: eu-west-1

managedNodeGroups:
  - name: ca-ng-spot-01
    labels: { role: workers }
    instanceTypes: ["c3.large","c4.large","c5.large","c5d.large","c5n.large","c5a.large"]
    spot: true
  - name: ca-ng-02
    labels: { role: ondemand }
    instanceSelector:
      vCPUs: 8
      memory: "16"
    minSize: 1
    desiredCapacity: 1
    maxSize: 450
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cas: "owned"