apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: spot
spec:
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot"]
      - key: capacity-spread
        operator: In
        values:
        - "3"
        - "4"
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      kubelet:
        maxPods: 30
  disruption:
    consolidationPolicy: WhenUnderutilized
  limits:
    cpu: "500"